### PR TITLE
Add new experiment color-toj-negation-06.js and fix parsing of JSON in introduction.js

### PR DESCRIPTION
**Pull request by m-neuss**
The new color-toj-negation-06 experiment integrates the experiment color-toj-negation-02 into the advanced code structure from color-toj-negation-05. 

The app crashed after the first activation of the continue button because the data submitted by the user was not converted into a String before being parsed as a JSON. This is now fixed.

### CODE REVIEW

**Review by caiusno1 — CHANGES_REQUESTED** [review]
JSON.stringify and JSON.parse are inverse operations. Therefore a pair of them can allways be skipped. 

const responses = trial.responses;
should do the job

Edit: Actually it (exp.6) do not work for me anymore because **trial.responses** contains data not **trial.response**

**Review by caiusno1 — APPROVED** [review]

**Review by caiusno1 — CHANGES_REQUESTED** [review]
const responses = trial.responses;
should be 
const responses = JSON.parse(trial.responses);

as discussed ... I am sry :/

**Comment by chisburger** [comment]
> const responses = trial.responses;
> should be
> const responses = JSON.parse(trial.responses);

Initially, 
`const responses = JSON.parse(trial.responses);`
worked on my system. A few hours later, only 
`const responses = trial.response;`
worked. I am still puzzled, why. In the meantime I did not update any packages. It is worth noting that the console complained about using a deprecated function to detect key presses which definitely does not used to happen with jspsych@6.3.1. Does npm silently updates packages? This may be also the reason why answers are always detected as being "wrong" (hence the sound for a wrong answer in the tutorial).

**Comment by m-neuss** [comment]
> > const responses = trial.responses;
> > should be
> > const responses = JSON.parse(trial.responses);
> 
> Initially, `const responses = JSON.parse(trial.responses);` worked on my system. A few hours later, only `const responses = trial.response;` worked. I am still puzzled, why. In the meantime I did not update any packages. It is worth noting that the console complained about using a deprecated function to detect key presses which was definitely not with jspsych@6.3.1. Does npm silently updates packages?

I noticed almost exactly the same behaviour. Initially
`const responses = JSON.parse(trial.responses);`
didn't work on my system. So I changed it to 66e540e which worked fine for me. 

After I pushed the changes and @caiusno1 pointed out, that my changes did not work on his system, I cloned my 66e540e push, installed needed npm packages and tried to run it. Now it did not work on my system either. So I tried reverting to the original implementation with
`const responses = JSON.parse(trial.responses);`
and it ran perfectly fine.

If I do this revert to 
`const responses = JSON.parse(trial.responses);`
in my initial working directory, which i did not change after I pushed 66e540e (so it should be identical to my clone), it does not run because of the same SyntaxError I got after I forked initially.

I can also confirm, that 
> answers are always detected as being "wrong"

seems to relate with this bug, because the behaviour of correct audio feedback changed on my system, too. It did not work properly on 66e540e, but worked perfectly fine, after I cloned this exact push and reverted back to 
`const responses = JSON.parse(trial.responses);`

**Review by caiusno1 — APPROVED** [review]

**Comment by caiusno1** [comment]
As @chisburger found out it is likely that the version we use (github vs. npm) decides how the trial.response is encoded and therefore how it can be used (or processed). If we stay with the github version the initial version should work of introduction.js should work as "trial.response" is a string then.
In the other version "trial.response" is an object and should not be decoded or "reencoded". At least that is my understanding...

I would decide for using the **npm** version if there is no complain

**Pull request merged**
